spring:
  config:
    activate:
      on-profile:
        - local
  custom:
    greet: "Test local"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/chatting_app
