spring:
  application:
    name: chatting
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Welcome1!
    url: jdbc:mariadb://localhost:3306/chatting_app
  mvc:
    static-path-pattern: classpath:/static/**
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    template-loader-path: classpath:/templates/
    enabled: true
    check-template-location: true
    thymeleaf-layout-dialect:
      enabled: true

logging:
  level:
    root: info
# mybatis:
#   mapper-locations:
#     - classpath:mapper/**/*.xml
#     - classpath:mapper/*.xml
#   configuration:
#     map-underscore-to-camel-case: true
#   type-aliases-package: com.app.board.dev.board_app.board.dto
