spring:
  config:
    activate:
      on-profile:
        - dev
  custom:
    greet: "Test dev"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Welcome1!
    url: jdbc:mariadb://localhost:3306/chatting_app